name: indecs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - cudatoolkit=11.8
  - opencv
  - pandas
  - numpy
  - scipy
  - python-dotenv
  - pip:
    - mmcv-full
    - mmdet
    - "git+https://github.com/open-mmlab/mmdetection.git"